added default option in case

diff --git a/genscript/genscript b/genscript/genscript
--- a/genscript/genscript
+++ b/genscript/genscript
@@ -22,6 +22,12 @@ while [ "$#" -gt 0 ] && [[ "$1" == -* ]]; do
 			display_help
 			exit 0
 			;;
+		*)
+			echo "Invalid option: $1" >&2
+			display_help
+			exit -1
+			;;
+
 	esac
 	shift
 done
